services:
  postgres:
    image: postgres:15
    container_name: oumaima-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giftlist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: oumaima-backend
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/giftlist?sslmode=disable"
    ports:
      - "8000:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: oumaima-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
