services:
  backend:
    build: ./backend
    container_name: oumaima-backend
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/gifts
    ports:
      - "8000:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: oumaima-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: oumaima-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gifts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
